version: 2.1

jobs:
  deploy:
    docker:
        - image: cimg/node:22.19.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v3-dependence-{{ checksum "package-lock.json" }}
          - v3-dependence-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v3-dependence-{{ checksum "package-lock.json" }}
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy at netlify
          command: npm run deploy


workflows:
  build_deploy:
    jobs:
      - deploy